### ISSUE TITLE
python 3 incompatibility in setup_cifar.py

### ISSUE THREAD

**Issue by jcpeterson** [revbucket/mister_ed#12]
`except OSError, err: ` doesn't work in python3

**Comment by tianweiy** [comment]
We will fix this soon.

**Comment by jcpeterson** [comment]
also: `urllib2`

**Comment by tianweiy** [comment]
yes, someone points out that urllib2 is not a good library. We may change this to urllib.request or request library

**Comment by revbucket** [comment]
Sorry! Growing pains! (I'm new to python3 after almost a decade of python2 programming)

This is fixed now (thanks for your patience!)

**Comment by jcpeterson** [comment]
Thanks!
