### ISSUE TITLE
TODO: Build setup_mnist.py

### ISSUE THREAD

**Issue by revbucket** [revbucket/mister_ed#14]
I have a setup_cifar.py file. Building some pretrained models and setup scripts for MNIST is probably useful for people wanting to get `mister_ed` running out of the box

**Comment by tianweiy** [comment]
I can do this this week or weekend as I also need to train a model for ALP on MNIST. I think we don't need much pretrained models for MNIST as most are similar and sufficient to get 99.3% accuracy. Support for MNIST is good for a sanity test of attack and defense methods.

**Comment by tianweiy** [comment]
Hi, I have written most of the code needed for MNIST support. Can you create a branch so that I can create a pull request?

**Comment by tianweiy** [comment]
You can see my folk repository's last two commits to get a glance of changes that I made. I didn't write method to get parameters yet. I change the setup_cifar to a general setup script and we still need to change the README.md

**Comment by revbucket** [comment]
Looks good. Thanks! 

I've made a general branch `tianwei` for your updates. If you submit a pull request for the setup script, I'll fold it in. Let's get some pretrained models built and hosted too. Currently I think I just have the cifar nets hosted on my personal dropbox: there's probably a better way to do this.
