### ISSUE TITLE
attack_specific_params not set to anything in tutorial 3

### ISSUE THREAD

**Issue by jcpeterson** [revbucket/mister_ed#19]
`attack_specific_params=` is not set to anything

**Comment by tianweiy** [comment]
Hi, what do you mean by not setting to anything? Do you mean that there is a mistake that we forget to set the attack_specific_params(if it is, can you tell me the specific location, I take a glance and haven't found it) Or you mean the attack_specific_params is not used later?

**Comment by jcpeterson** [comment]
scratch that

**Comment by revbucket** [comment]
This was spurious, correct? It's just kinda messy when the lines are so long. Still trying to nail down proper coding style in jupyter notebooks.
