### ISSUE TITLE
Can't use GPU for spatial transformation in Tutorial 1

### ISSUE THREAD

**Issue by tianweiy** [revbucket/mister_ed#6]
When I try the PGD stAdv attack in the first tutorial, I get the following error.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-89f5da47cd39> in <module>
      1 pgd_attack_obj = aar.PGD(model, normalizer, flow_threat, flow_attack_loss)
      2 flow_perturbation = pgd_attack_obj.attack(examples, labels, num_iterations=20, signed=False, 
----> 3                                           optimizer=optim.Adam, optimizer_kwargs={'lr': 0.001}, verbose=True)

~/Documents/deep_learning/AE/mister_ed/adversarial_attacks_refactor.py in attack(self, examples, labels, step_size, num_iterations, random_init, signed, optimizer, optimizer_kwargs, loss_convergence, verbose, keep_best)
    350         for iter_no in range(max_iterations):
    351             perturbation.zero_grad()
--> 352             loss = self.loss_fxn.forward(perturbation(var_examples), var_labels,
    353                                          perturbation=perturbation,
    354                                          output_per_example=keep_best)

~/Documents/deep_learning/AE/mister_ed/adversarial_perturbations.py in __call__(self, x)
     63 
     64     def __call__(self, x):
---> 65         return self.forward(x)
     66 
     67     def __repr__(self):

~/Documents/deep_learning/AE/mister_ed/adversarial_perturbations.py in forward(self, x)
    620             self.setup(x)
    621         self.constrain_params()
--> 622         return self.xform.forward(x)
    623 
    624 

~/Documents/deep_learning/AE/mister_ed/spatial_transformers.py in forward(self, x)
    279     def forward(self, x):
    280         # usual forward technique
--> 281         return F.grid_sample(x, self.xform_params)
    282 
    283 

~/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py in grid_sample(input, grid, mode, padding_mode)
   2091     else:
   2092         raise ValueError("padding_mode needs to be 'zeros' or 'border', but got {}".format(padding_mode))
-> 2093     return torch.grid_sampler(input, grid, padding_mode)
   2094 
   2095 

RuntimeError: Tensor for argument #2 'grid' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_grid_sampler_forward)
```

If i change the self.xform_params to self.xform.params.cuda(), it throws the following error.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-89f5da47cd39> in <module>
      1 pgd_attack_obj = aar.PGD(model, normalizer, flow_threat, flow_attack_loss)
      2 flow_perturbation = pgd_attack_obj.attack(examples, labels, num_iterations=20, signed=False, 
----> 3                                           optimizer=optim.Adam, optimizer_kwargs={'lr': 0.001}, verbose=True)

~/Documents/deep_learning/AE/mister_ed/adversarial_attacks_refactor.py in attack(self, examples, labels, step_size, num_iterations, random_init, signed, optimizer, optimizer_kwargs, loss_convergence, verbose, keep_best)
    352             loss = self.loss_fxn.forward(perturbation(var_examples), var_labels,
    353                                          perturbation=perturbation,
--> 354                                          output_per_example=keep_best)
    355             loss_per_example = loss
    356             loss = loss.sum()

~/Documents/deep_learning/AE/mister_ed/loss_functions.py in forward(self, examples, labels, *args, **kwargs)
     59                 output = addendum
     60             else:
---> 61                 output = output + addendum
     62         if self.negate:
     63             return output * -1

RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.FloatTensor for argument #3 'other'
```

The script works find if I turn off the gpu use by changing the global variable

**Comment by tianweiy** [comment]
I haven't looked deep into the code yet. I try to set_global_gpu(True) and this time it throws another error
```
~/miniconda3/envs/maskrcnn_benchmark/lib/python3.7/site-packages/torch/nn/functional.py in grid_sample(input, grid, mode, padding_mode)
   2238                          "but got: '{}'".format(padding_mode))
   2239     return torch.grid_sampler(input, grid, GRID_SAMPLE_INTERPOLATION_MODES[mode],
-> 2240                               GRID_SAMPLE_PADDING_MODES[padding_mode])
   2241 
   2242 

RuntimeError: grid_sampler(): expected input and grid to be on same device, but input is on cuda:0 and grid is on cpu
```  

I haven't looked into the several components yet but I think there may be some problems like initialize the optimizer before we create those parameters.

**Comment by tianweiy** [comment]
It seems that I have used some wrong value for use_gpu. I ran the tutorial a few hours later and it is fine now

**Comment by revbucket** [comment]
Okay, I'll take a look into this (even though you said everything's working now). I recently changed the GPU settings to require less passing-around of `use_gpu` keywords, but there may be some things that fell through the cracks. 

To be clear, you're using a machine with a GPU and running the following outputs True? (and you do want to use the GPU for the tutorial?)
`python3 -c 'import torch.cuda; print(torch.cuda.is_available())'`

(also, I see you're a student at UT. We can meet up in person if you have any bugs that persist or if you have any questions about mister_ed. I'm also open to collaborating on research projects :D )

**Comment by tianweiy** [comment]
Hi Matt Jordan, Yes, I use gpu to run the tutorials and it works fine now. I don't know why at the beginning it doesn't work well. I have looked at the whole path of the execution and may have some tiny changes that I don't remember to remove. But it just works now :D. One suggestion is that you can print out some information when the GPU is not set manually. I just re downloaded from your git repository and the problem is still there. I have to go to an anthropology course now, and I will respond the other stuff later.

**Comment by revbucket** [comment]
Reopened and fixed this. Thanks for pointing out this bug!

Here's the explanation of what went wrong:
I forgot to change some default behavior when I pulled out the `use_gpu` keywords a few weeks ago and this caused some problems upon initializing an AdversarialPerturbation object. The spatial trasformation is a `ParameterizedXformAdv` which holds onto spatial transformation parameters, which are held in a `FullSpatial` instance, initialized like this (line 555 of adversarial_perturbations.py)
```
        self.xform = self.perturbation_params.xform_class(shape=originals.shape,
                                                        manual_gpu=self.use_gpu)
```

Since the default behavior of `use_gpu` used to be `False` (instead of the system default), this initalized the parameters of the flow attack as CPU tensors instead of GPU ones. See the fix in the commit to see where this default behavior was changed:
https://github.com/revbucket/mister_ed/commit/7495504e6334af0d1c61415fb3b94fdfe1131ff6

**Comment by tianweiy** [comment]
That's the cause. I just found out I add a use_gpu=true flag when I initialize which solves the problem. I am a freshman in the CS department and I am referred to this toolbox by professor Alex Dimakis(your advisor I think). Currently, I have read some papers about AE but I don't have much programming experience so I just want to understand this toolbox and try to contribute to it. If you are available, shall we find some time tomorrow to discuss the future development of this toolbox? I have some ideas about some new components and I can learn and test the program while running experiments. You can contact me at my ut email: yintianwei@utexas.edu
