### ISSUE TITLE
AttributeError: 'builtin_function_or_method' object has no attribute '_TensorBase'

### ISSUE THREAD

**Issue by tianweiy** [revbucket/mister_ed#7]
Please change the safe_var method in pytorch_utils.py
From

`elif isinstance(entity, torch.tensor._TensorBase):
        return Variable(entity, **kwargs)`

to

`elif isinstance(entity, torch._C._TensorBase):
        return Variable(entity, **kwargs)`

Please also change safe_tensor method.

It seems that since pytorch 0.4.0, the original tensor._TensorBase has been replaced by ._C.TensorBase.

**Comment by revbucket** [comment]
These are leftover techniques from back when there was a difference between Variable and Tensors (pytorch <=0.3.0). I've removed all calls to functions throughout and added DeprecationWarnings to the functions themselves.
