### ISSUE TITLE
main_sandbox.py is Outdated

### ISSUE THREAD

**Issue by tianweiy** [revbucket/mister_ed#8]
The main_sandbox.py is outdated as it doesn't take threat_model as parameters. I can submit a commit to fix the file if needed

**Comment by revbucket** [comment]
Yep. I've implicitly deprecated main_sandbox and in general favor using jupyter notebooks for all exploration/experiments. Going forward, I think the only scripts (as opposed to jupyter notebooks) that I'll be maintaining are things that will typically be tmuxed into the background (e.g. the contents of `mister_ed/scripts`, which contains scripts for training)

**Comment by revbucket** [comment]
Though it seems like you've updated the main_sandbox.py file, so I'll give that a quick spot-check and then close this issue. Thanks!

**Comment by tianweiy** [comment]
Yes, I think this is a better idea. We just need to maintain the scripts in the script folder and deprecate sandbox files
